### ISSUE TITLE
You cannot have duplicated devices in mirroredBoots

### ISSUE THREAD

**Issue by erictapen** [freifunkMUC/infra#2]
This is a really exiting way of describing Freifunk infra. At the moment, I encounter the following error on my laptop:

```
$ make
nix-build -I nixpkgs=https://github.com/mayflower/nixpkgs/archive/master.tar.gz
error:
Failed assertions:
- You cannot have duplicated devices in mirroredBoots
(use ‘--show-trace’ to show detailed location information)
make: *** [Makefile:2: default] Error 1
```

Did I oversee something?

**Comment by awlx** [comment]
We are working on a restructure of the infrastructure atm. So I'll close this as it won't be relevant anymore.
